module.exports = {
  ':root': 1
, ':nth-child': 1
, ':nth-last-child': 1
, ':nth-of-type': 1
, ':nth-last-of-type': 1
, ':first-child': 1
, ':last-child': 1
, ':first-of-type': 1
, ':last-of-type': 1
, ':only-child': 1
, ':only-of-type': 1
, ':first-line': 1
, ':first-letter': 1
, ':before': 1
, ':after': 1
, ':empty': 1
, ':link': 1
, ':visited': 1
, ':active': 1
, ':hover': 1
, ':focus': 1
, ':target': 1
, ':lang': 1
, ':enabled': 1
, ':disabled': 1
, ':checked': 1
, ':not': 1
}